server:
  port: 8199
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/samaraweera/spring-cloud-config-store
          #username: - If you use private repo then need this.
          #password:
          search-paths:
            - '*service'
            # why used '*service' search inside directories (spring-cloud-config-store ->mem-service)
            # inside the spring-cloud-config-store project every service end with the service

